version: '3'

services:

### Applications Code Container #############################

    app:
      image: tianon/true
      volumes:
        - applications-sync:/var/www:nocopy # nocopy is required

### Volumes Setup #############################################

volumes:
  applications-sync:
    external:
      name: "applications-docker-sync"
