version: '2'

services:
  # Applications Code
  app:
    image: tianon/true
    volumes:
      - ${APPLICATION}:/var/www

  # Workspace Utilities
  workspace:
    build: 
      context: ./etc/workspace
      args:
        - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
        - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - TZ=${WORKSPACE_TIMEZONE}
      dockerfile: "Dockerfile-${PHP_VERSION}"
    volumes_from:
      - app
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    tty: true
    networks:
      - frontend
      - backend

  # Instance PHP
  php:
    build: 
      context: ./etc/php
      args:
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
      dockerfile: "Dockerfile-${PHP_VERSION}"
    volumes_from:
      - app
    volumes:
      - ${PHP_LOG_PATH}:/var/log/php
    expose:
        - "9000"
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    networks:
      - backend

  # Instance Nginx
  nginx:
    build: 
      context: ./etc/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    volumes_from:
      - app
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    links:
      - mapserver
    depends_on:
      - php
    networks:
      - frontend
      - backend

  # Instance DB
  db:
    build: ./etc/db
    volumes:
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_LOG_PATH}:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend

  # Instance MapServer
  mapserver:
    build: ./etc/mapserver
    volumes_from:
      - app
    volumes:
      - ${MAPSERVER_DATA}:/usr/local/share/mapserver
      - ${MAPSERVER_LOG_PATH}:/var/log/mapserver
    ports:
      - ${MAPSERVER_HOST_HTTP_PORT}:8080
    networks:
      - backend


# Networks Setup
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"