  # Instance MapServer
  mapserver:
    build: ./etc/mapserver
    ports:
      - 8080:8080
    volumes:
      - ./usr/geo/mapserver:/usr/local/share/mapserver
      - ./usr/geo/mapcache:/usr/local/share/mapcache
      - ./usr/log/mapserver:/var/log/mapserver
    tty: true


  ### Stack Optimisation ###
  # Instance Redis
  redis:
    image: redis
    ports:
      - 6379:6379
    tty: true 

  # Instance RabbitMQ
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


  ### ELK Stack ###
  # Instance ElasticSearch
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300


  ### Tools for Dev ###
  # Instance MailDev
  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80

  # Instance Blackfire
  blackfire:
    image: blackfire/blackfire
    ports:
      - 8707:8707