version: '3'

services:
  # Instance Web
  web:
    build: ./etc/nginx
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./usr/www/:/var/www/html
      - ./usr/log/nginx:/var/log/nginx

  # Instance PHP
  php:
    build: ./etc/php
    ports:
      - 9000:9000
    volumes:
      - ./usr/www/:/var/www/html
      - ./usr/log/php:/var/log/php

  # Instance DB
  db:
    image: mdillon/postgis
    ports:
      - 5432:5432
    volumes:
      - ./usr/log/pgsql:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres


  ### Stack Optimisation ###
  # Instance Redis
  redis:
    image: redis
    ports:
      - 6379:6379

  # Instance RabbitMQ
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


  ### ELK Stack ###
  # Instance ElasticSearch
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300


  ### Tools for Dev ###
  # Instance MailDev
  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80

  # Instance Blackfire
  blackfire:
    image: blackfire/blackfire
    ports:
      - 8707:8707
