version: '3'

services:
  # Instance Web
  web:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./usr/www/:/var/www/html
      - ./usr/log/nginx:/var/log/nginx

  # Instance PHP
  php:
    restart: always
    image: php:5.6.31-fpm
    ports:
      - 9000:9000
    volumes:
      - ./usr/www/:/var/www/html
      - ./usr/log/php:/var/log/php

  # Instance DB
  db:
    restart: always
    image: mdillon/postgis
    ports:
      - 5432:5432
    volumes:
      - ./usr/log/pgsql:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=


  ### Stack Optimisation ###
  # Instance Redis
  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379

  # Instance RabbitMQ
  rabbitmq:
    restart: always
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


  ### ELK Stack ###
  # Instance ElasticSearch
  elasticsearch:
    restart: always
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300


  ### Tools for Dev ###
  # Instance MailDev
  maildev:
    restart: always
    image: djfarrelly/maildev
    ports:
      - 1080:80
