
  ### Stack Optimisation ###
  # Instance RabbitMQ
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


  ### ELK Stack ###
  # Instance ElasticSearch
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300


  ### Tools for Dev ###
  # Instance Blackfire
  blackfire:
    image: blackfire/blackfire
    ports:
      - 8707:8707